config/routes.rb
Rails.application.routes.draw do

  root "task_lists#index"

  # Rotas para TaskLists
  get "/task_lists/:id", to: "task_lists#show", as: :task_list
  post "/task_list", to: "task_lists#create", as: :task_lists
  delete "/task_lists/:id", to: "task_lists#destroy"
  #get "/blog_posts/:new", to: "blog_posts#new", as: :new_blog_post
  #patch "blog_posts/:id", to: "blog_posts#update"
  #get "/blog_posts/:id/:edit/", to: "blog_posts#edit", as: :edit_blog_post

  # Rotas para Tasks
  post "/task_lists/:task_list_id/tasks", to: "tasks#create", as: :task_list_tasks
  get "/task_lists/:task_list_id/tasks/:id/edit", to: "tasks#edit", as: :edit_task_list_task
  get "/task_lists/:task_list_id/tasks/new", to: "tasks#new", as: :new_task_list_task
  patch "/task_lists/:task_list_id/tasks/:id", to: "tasks#update", as: :task_list_task
  delete "/task_lists/:task_list_id/tasks/:id", to: "tasks#destroy", as: :task_list_task_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_list
  validates :title, presence: true
end

app/models/task_list.rb
class TaskList < ApplicationRecord
    has_many :tasks, dependent: :destroy    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
    before_action :set_task_list, only: [:show, :destroy]

    def index
        @task_lists = TaskList.all
        @task_list = TaskList.new
    end

    def show
        @new_task = Task.new
    end

    
    def create
        @task_list = TaskList.new(task_list_params)
        if @task_list.save
            redirect_to "#index"
        else
            render :new, status: :unprocessable_entity 
        end
    end

    def destroy
        @task_list.destroy
        redirect_to "#index"
    end

    private

    def set_task_list
        @task_list = TaskList.find(params[:id])
    end

    def task_list_params
        params.require(:task_list).permit(:name)
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task_list
  before_action :set_task, only: [:edit, :update, :destroy]

  def create
    @task = @task_list.tasks.build(task_params)
    if @task.save
      redirect_to task_list_path(@task_list)
    else
      render "task_lists/show", status: :unprocessable_entity
    end
  end

  def new
    @new_task = Task.new 
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to task_list_path(@task_list)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    redirect_to task_list_path(@task_list)
  end

  private

  def set_task_list
    @task_list = TaskList.find(params[:task_list_id])
  end

  def set_task
    @task = @task_list.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/task_lists/_form.html.erb
<%= form_with model: @task_list do |form| %>

    <% if form.object.errors.any? %>
        <div>
        <% form.object.errors.full_messages.each do |message| %>
            <div><%= message %> </div>
        <% end %>
        </div>
    <% end %>

    <div>
        <%= form.label :name%>
        <%= form.text_field :name%>
        <%= form.button%>
    </div>

<%end%>

app/views/task_lists/index.html.erb
<h1>Your Task Lists</h1>

<%= render 'form', task_list: @task_list %>

<ul>
  <% @task_lists.each do |task_list| %>
    <li>
      <div>
        <%=link_to task_list.name, task_list_path(task_list)%>
        <%= button_to "Delete", task_list_path(task_list), method: :delete, data: {turbo_confirm: "Are you sure?"}%>
      </div>
    </li>
  <% end %>
</ul>

app/views/task_lists/show.html.erb
<h1> <%= @task_list.name%> </h1>

<h2>Tasks</h2>

<%= render 'tasks/form',  task: @new_task %>

<ul>
  <% @task_list.tasks.each do |task| %>
    <li>
      <div>
        <%= render 'tasks/checkbox',  task: task %>
        <%= button_to "Delete", task_list_task_delete_path(@task_list, task.id), method: :delete, data: {turbo_confirm: "Are you sure?"}%>      
      </div>
    </li>
  <% end %>
</ul>

app/views/tasks/_checkbox.erb
<%= form_with model: task, url: task_list_task_path(@task_list, task), method: :patch, local: true do |f| %>
  <%= f.label :completed %>:
  <%= f.check_box :completed %><br />
  <%= f.submit %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with model: [ @task_list, task ], local: true do |form| %>
  <% if task.errors.any? %>
    <div>
      <% task.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.submit 'Add Task' %>
  </div>
<% end %>